// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uhRnpzRclfMAx4iRCKSPGyCQ7eNHKGs',
    appId: '1:770121627786:web:1de456b27659d7aeab1573',
    messagingSenderId: '770121627786',
    projectId: 'socialmedia-60e45',
    authDomain: 'socialmedia-60e45.firebaseapp.com',
    storageBucket: 'socialmedia-60e45.appspot.com',
    measurementId: 'G-1V6JGWW0ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPmNmVNslq2NWWlT8e2OZWONabH6DzUE',
    appId: '1:770121627786:android:60f2cfdbc65de017ab1573',
    messagingSenderId: '770121627786',
    projectId: 'socialmedia-60e45',
    storageBucket: 'socialmedia-60e45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbMWKCnD0i5kgtC_KdD9L4UoHKDrNmxk',
    appId: '1:770121627786:ios:df55a68ac8f43333ab1573',
    messagingSenderId: '770121627786',
    projectId: 'socialmedia-60e45',
    storageBucket: 'socialmedia-60e45.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbMWKCnD0i5kgtC_KdD9L4UoHKDrNmxk',
    appId: '1:770121627786:ios:df55a68ac8f43333ab1573',
    messagingSenderId: '770121627786',
    projectId: 'socialmedia-60e45',
    storageBucket: 'socialmedia-60e45.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8uhRnpzRclfMAx4iRCKSPGyCQ7eNHKGs',
    appId: '1:770121627786:web:2eee3f2086e449f5ab1573',
    messagingSenderId: '770121627786',
    projectId: 'socialmedia-60e45',
    authDomain: 'socialmedia-60e45.firebaseapp.com',
    storageBucket: 'socialmedia-60e45.appspot.com',
    measurementId: 'G-J5L6G340HK',
  );


}
